version: '3.8'

services:
  discovery:
    image: anasodev/discovery-img
    ports:
      - "8761:8761"

  gateway:
    image: anasodev/gateway-img:dev
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/

  customer:
    image: anasodev/customer-img:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://customer-db:3306/customers-db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - customer-db
      - discovery

  customer-db:
    image: mysql:latest
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customers-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

  inventory:
    image: anasodev/inventory-img:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://inventory-db:3306/products-db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - inventory-db
      - discovery

  inventory-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      DATABASE_HOST: docker-mysql2
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

