#  mvn clean install -Dspring.profiles.active=dev
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
server:
  port: 8081

