server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}