spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anasoualkadi/microservices-config
    discovery:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 9999
